baseURL = "https://albin-express-experience.pages.dev/"
languageCode = "en"
title = "Albin Express 'Experience'"

defaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "EN"
    weight = 1
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = "Go sailing"
        pageRef = "/"
        weight = 1
      [[languages.en.menus.main]]
        name = "Logbook"
        pageRef = "/logbook"
        weight = 2
      [[languages.en.menus.main]]
        name = "Captain"
        pageRef = "/captain"
        weight = 3
      [[languages.en.menus.main]]
        name = "Docs"
        pageRef = "/docs"
        weight = 4
  [languages.fi]
    languageName = "FI"
    weight = 2
    [languages.fi.menus]
      [[languages.fi.menus.main]]
        name = "Purjehtimaan"
        pageRef = "/"
        weight = 1
      [[languages.fi.menus.main]]
        name = "Lokikirja"
        pageRef = "/logbook"
        weight = 2
      [[languages.fi.menus.main]]
        name = "Kippari"
        pageRef = "/captain"
        weight = 3
      [[languages.fi.menus.main]]
        name = "Dokumentaatio"
        pageRef = "/docs"
        weight = 4

[taxonomies]

[params]
  description = "1990 Albin Express Jubilee 'Experience'"
  contactEmail = "henri.ruoho@gmail.com"
