baseURL = "https://hruoho.github.io/albin-express-experience/"
languageCode = "en"
title = "Albin Express Experience"

defaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "EN"
    weight = 1
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = "Home"
        pageRef = "/"
        weight = 1
      [[languages.en.menus.main]]
        name = "Logbook"
        pageRef = "/logbook"
        weight = 2
      [[languages.en.menus.main]]
        name = "Docs"
        pageRef = "/docs"
        weight = 3
  [languages.fi]
    languageName = "FI"
    weight = 2
    [languages.fi.menus]
      [[languages.fi.menus.main]]
        name = "Koti"
        pageRef = "/"
        weight = 1
      [[languages.fi.menus.main]]
        name = "Lokikirja"
        pageRef = "/logbook"
        weight = 2
      [[languages.fi.menus.main]]
        name = "Dokumentaatio"
        pageRef = "/docs"
        weight = 3

[params]
  description = "1990 Albin Express â€” Charter & Sale"
  contactEmail = "REPLACE_ME"
